# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-08 17:05
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('from_json', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created_time', models.DateTimeField()),
                ('message', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graph.Post')),
            ],
        ),
    ]
