# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-08 23:00
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0003_auto_20160908_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('title', models.TextField()),
                ('type', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('media', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('target', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('description_tags', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('subattachments', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graph.Post')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='attachment',
            unique_together=set([('post', 'title')]),
        ),
    ]
