# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-09 21:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0006_comment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='graph.Post'),
        ),
    ]
