# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-02 14:54
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('graph', '0007_auto_20160909_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('updated_time', models.DateTimeField()),
                ('from_data', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('to_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('message', models.TextField()),
                ('unread', models.IntegerField()),
                ('unseen', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
