workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master

version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.8-jessie-node
        environment:
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
          DJANGO_SETTINGS_MODULE: analysocial.settings
          DJANGO_DEBUG: 1
          DJANGO_ENABLE_SSL: 0
      - image: circleci/postgres:9.6.5-alpine-ram
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout
      - restore_cache:
          key: deps-py-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - restore_cache:
          key: deps-npm-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          # https://discuss.circleci.com/t/circleci-python-docker-images-disallow-pip-install-due-to-directory-ownership/12504
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps-py-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - save_cache:
          key: deps-npm-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      - run:
          command: |
            npm install
            . venv/bin/activate
            flake8
            node_modules/.bin/jshint */static/*/js
            coverage run manage.py test
            PYTHONPATH=. coveralls
  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | bash
            bash scripts/deploy_to_heroku.sh circle
